### ISSUE TITLE
Update nicht möglich

### ISSUE THREAD

**Issue by Uli1900** [nielstron/diy_bayernluft#2]

**Comment by Yannik25** [comment]
Hallo Uli1900, 
kann es sein, dass du https://github.com/mampfes/ha_bayernluefter nutzt?
Dort hat mampfen eine update Funktion hinzugefügt, bei unserer Version wird dies nicht unterstützt

**Comment by Uli1900** [comment]
Du hast recht - hier ist es falsch. Habe es rüberkopiert. Kann das hier nicht löschen.
